### ISSUE TITLE
g++ no longer included

### ISSUE THREAD

**Issue by ghost** [frol/docker-alpine-gcc#1]
If you're going to separate g++ into its own image, you need to tell the community before you do so.

Our company was going to deploy with this image. We were using g++ with this image, and all of a sudden our tests started failing, and we didn't know why.

I had to come to this GitHub page, and by chance saw the commit message on the README. There would have been no other way that I know of to know that you were removing g++ from this image.

EDIT: At the very least, implement tags, such that we can make sure we are getting the same version every time.

**Comment by frol** [comment]
I was trying to come up with an announcement, but I failed to think of any media I could declare the breaking change. I am sorry that you have experienced this breaking change. I hope the simple change from `frolvlad/alpine-gcc` to `frovlad/alpine-gxx` worked fine for you.

**Comment by ghost** [comment]
Well, at the very least, an explanation in the README would be a good idea. Also, do you not have the power to announce anything via Docker Hub? (You may not, I've never published anything there myself.)

The move to alpine-gxx worked as a quick fix, but I think it made us realize that the long term solution is to just roll our own Docker images. (If this was in production, it would have broken our software - that's a huge risk.)
