### ISSUE TITLE
i can't create container from images

### ISSUE THREAD

**Issue by skyphantomhz** [frol/docker-alpine-gcc#2]
[mastermind@lenovo ~]$ docker run frolvlad/alpine-gcc
docker: Error response from daemon: No command specified.
See 'docker run --help'.

thank you!

**Comment by frol** [comment]
So... "No command specified". What did you expect?

There is a usage example right in the README:

1. Create a test.c file with the following content:

    ```c
    #include <stdio.h>
    int main() {
        printf("Hello World\\n");
    }
    ```
2. Compile it:

    ```
    docker run --rm -v `pwd`:/tmp frolvlad/alpine-gcc gcc --static /tmp/test.c -o /tmp/test
    ```
