### ISSUE TITLE
FREQ: Customized alpine image w/ preconfigured multiple NICS or aliases

### ISSUE THREAD

**Issue by adam-law** [frol/docker-alpine-gcc#3]
Hi,

Thanks for this image!

Due to the limitations in Docker build, there is no way to run privileged actions. It's been years since this feature request was posted, but it's a foregone conclusion that Docker will not be implementing this feature anytime soon.

Since I can't run ifconfig/ip to add virtual interfaces and/or ip aliases to eth0, during docker build, I was hoping to circumvent this limitation at the image level i.e. alpine with at least 2 NICs or alpine's eth0 with at least one alias.

For my use case, it would allow me to host a STUN server, without having to fire up another instance, just so each would have a secondary STUN ip, in compliance with RFC 5389.

I'm sure others out there have a need for such an image. If there was some way for a user to customize the IPs/NICs, it would be ideal.

**Comment by frol** [comment]
@adam-law How is this GCC image related to the issue you describe?

**Comment by adam-law** [comment]
@frol Sorry, I was away, and if this was a noob question. I wanted to know how to modify the image in order for it to have the aforementioned settings in it. Without it, there's currently no easy way to tell Docker, or services like Kubernetes to deploy an image with these settings.

For exampled Dockerfile does not allow me to run ifconfig / ip, which would make what I want to do, trivial.

**Comment by frol** [comment]
You can implement a custom entrypoint script, which will be executed on the container start.

**Comment by adam-law** [comment]
👍 Thank you for the suggestion @frol. I did come across that option, though my preference is obvious. I'll explore this option then :) Still, great project!
